### ISSUE TITLE
Cannot set io.sails.header later.

### ISSUE THREAD

**Issue by vikas-0** [balderdashy/sails.io.js#123]
I have authorisation token in my redux store. I want to update the header once the value is available in store.
in one file i have
```
import socketIOClient from 'socket.io-client';
import sailsIOCLient from 'sails.io.js';
export const baseURL = 'http://localhost:1337/';

const io = sailsIOCLient(socketIOClient);
io.sails.url = baseURL;
io.sails.initialConnectionHeaders = { nosession: true };
io.sails.transports = ['websocket'];

export { io };

```

and in another file I want to update header
```
import {io} form 'xyz.js';
io.sails.header = {authorisation : '<value from store>';
io.socket.get('\url' (resp)=>{
console.log(resp)
})
```

the request is sent without headers;

**Comment by Noitidart** [comment]
Do you want to do requests before the header is available?

**Comment by vikas-0** [comment]
@Noitidart no
but I intend to use it in multiple places

**Comment by Noitidart** [comment]
Then you should set in the first file `io.sails.autoConnect` to false. Then in the 2nd file, after you set headers you have to do `io.sails.connect()`. Something like that.

**Comment by Noitidart** [comment]
So you have to set `initialConnectionHeaders`. Setting `.headers` are not real headers, they are just simulated headers: https://github.com/balderdashy/sails.io.js/blob/master/sails.io.js#L1466

**Comment by vikas-0** [comment]
> So you have to set `initialConnectionHeaders`. Setting `.headers` are not real headers, they are just simulated headers: https://github.com/balderdashy/sails.io.js/blob/master/sails.io.js#L1466

But initialConnectionHeaders Will not be sent with every request

**Comment by vikas-0** [comment]
> Then you should set in the first file `io.sails.autoConnect` to false. Then in the 2nd file, after you set headers you have to do `io.sails.connect()`. Something like that.

this helped. Just noticed , that the lib don't allow to modify properties after establishing connection.
