### ISSUE TITLE
CORS issue

### ISSUE THREAD

**Issue by mickyginger** [balderdashy/sails.io.js#37]
I'm using EmberCLI for my front end. I have included sails.io.js, and added the following code:
`io.sails.url = 'http://localhost:1337';`

But I get the following error:
`XMLHttpRequest cannot load http://localhost:1337/socket.io/?__sails_io_sdk_version=0.11.0&__sails_io_s…sails_io_sdk_language=javascript&EIO=3&transport=polling&t=1421409540966-5. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:4200' is therefore not allowed access.`

I have set `allRoutes: true` and `origin:'http://localhost:4200'` in `config/cors.js`, however I'm thinking that these settings only affect requests to the routes based on the comments in that file. I tried adding the headers in the `config/http.js` file using customMiddleware, but I get the same error.

**Comment by moehlone** [comment]
Same problem here. Tested with sails.js server v0.10.5 and sails io client 11.5. 

Server is running at http://localhost:1337 and clients at http://localhost. allRoutes is set to true.

Only when i use socket.io 0.9x OR sails io 0.10x it is working.

**Comment by quipu** [comment]
I've got this issue, too. Using server v0.10.5 and and sails io client 11.5. Same config as @moehlone

**Comment by everdance** [comment]
+1

**Comment by everdance** [comment]
Hey,  all, I found the problem, you should use the socket.io.js file in the generated sails project
**/assets/js/dependancies/sails.io.js**

Installing this module directly from bower just is not compatible with sails backend.

**Comment by sgress454** [comment]
Ah, thanks @everdance--this is correct.  The currently hosted `sails.io.js` is compatible with Sails v0.11.x only.  Sails v0.11 upgraded to use Socket.io 1.0, and we had to update the client to match.  You should *always* use the `sails.io.js` client that comes bundled with the version of Sails that you're using.  To upgrade later (if you upgrade your Sails app from v0.10.5 to v0.11.x), you can run `sails generate sails.io.js`.

Added a [note to the docs](https://github.com/balderdashy/sails.io.js/blob/master/README.md#installation) about using the proper version!
