### ISSUE TITLE
When client disconnects, return with error.

### ISSUE THREAD

**Issue by andyhu** [balderdashy/sails.io.js#38]
I have tried a scenario that after started a connection using io.socket.get (or any other methods), if the connection disconnects, the callback is never called, so I can't handle the error.
Here is the code I used to test. `/test-disconnect` is a route which never calls the response callback. Then when I shutdown sails, the callback function is not called. I would expect it returns the jwr object with `error` attribute provided
```js
io.socket.get('/test-disconnect', function(result, jwr) {
  // when disconnected, it's never called
}
```

**Comment by sgress454** [comment]
The best way to test for client disconnection is with the `io.socket.on('disconnect')` event.  You can also use the `io.socket._raw.connected` boolean property.  Both are preferable to trying a route and waiting for a response!
