### ISSUE TITLE
Why first setup polling and switch on to websocket?

### ISSUE THREAD

**Issue by psi-4ward** [balderdashy/sails.io.js#39]
https://github.com/balderdashy/sails.io.js/blob/master/sails.io.js#L945

Ill get two GET and two POST requests on every pageload before the upgrade

**Comment by sgress454** [comment]
Official explanation from the [engine.io core team](https://www.npmjs.com/package/engine.io#goals):

> The main goal of Engine is ensuring the most reliable realtime communication. Unlike the previous Socket.IO core, it always establishes a long-polling connection first, then tries to upgrade to better transports that are "tested" on the side.

>During the lifetime of the Socket.IO projects, we've found countless drawbacks to relying on HTML5 WebSocket or Flash Socket as the first connection mechanisms.

>Both are clearly the right way of establishing a bidirectional communication, with HTML5 WebSocket being the way of the future. However, to answer most business needs, alternative traditional HTTP 1.1 mechanisms are just as good as delivering the same solution.
