### ISSUE TITLE
Muting consolog / console.log messages

### ISSUE THREAD

**Issue by rmckeel** [balderdashy/sails.io.js#71]
Hello, I was just wondering if there is a clean way (without modifying sails.io.js) to mute the console log messages, and I couldn't find any info on this with web searches.  I would like visitors to not know immediately details of the stack they are using!

Thanks,

  Ryan

**Comment by rmckeel** [comment]
Hello, just checking again if anyone had ideas on this one.  Thanks!

**Comment by rmckeel** [comment]
OK, found the fix in sails.io.js line ~946.  As a request to the team, please put this in documentation!

      // The environment we're running in.
      // (logs are not displayed when this is set to 'production')
      // 
      // Defaults to development unless this script was fetched from a URL
      // that ends in `*.min.js` or '#production' (may also be manually overridden.)
      // 
      environment: urlThisScriptWasFetchedFrom.match(/(\#production|\.min\.js)/g) ? 'production' : 'development',

Thanks for making Sails an awesome open source product!

  Ryan

**Comment by sgress454** [comment]
@rmckeel if you make a PR to the README file with a note about the environment, we'd be happy to merge it in!

**Comment by rmckeel** [comment]
Great!  See https://github.com/balderdashy/sails.io.js/pull/75 for the new PR with README update.  Thanks!
