### ISSUE TITLE
No .removeListener(), only removeAllListeners() ?

### ISSUE THREAD

**Issue by cburatto** [balderdashy/sails.io.js#77]
My client code generates a unique socket listener per call, but I need to remove it after use to avoid too many listeners.
Socket.io has `.removeListener()`, but Sails.io seems to be missing that. Only `.removeAllListeners()` works.

**Comment by AKamanjha** [comment]
hey cburatto,
you can do it by adding following line of code in sails.io.js.
   
      SailsSocket.prototype.removeListener = function(listener){
        if(this._raw){
          this._raw.removeListener(listener);
          return this;
        }
        return this;
      }

Add the code after SailsSocket.prototype.removeAllListeners.

**Comment by sgress454** [comment]
You can now use [`.off()`](https://github.com/balderdashy/sails-docs/blob/0.12/reference/websockets/sails.io.js/io.socket.off.md) to remove listeners.

**Comment by cburatto** [comment]
Awesome, thanks.
