### ISSUE TITLE
autoConnect: false, delete sails instance

### ISSUE THREAD

**Issue by cojack** [balderdashy/sails.io.js#78]
https://github.com/balderdashy/sails.io.js/blob/master/sails.io.js#L1000

There is no posibility to connect after set option autoConnect to false, because you delete the socket instance, and function SailsSocket is internal function that we doesn't have access from outside.

**Comment by sgress454** [comment]
Make sure you [read the docs](https://github.com/balderdashy/sails.io.js#disable-autoconnect-andor-connect-sockets-manually)!  When autoConnect is `false`, you use `io.sails.connect()`, not `io.socket`.  All of the Sails core pubsub tests work this way, so it's pretty well tested.
