### ISSUE TITLE
Issue with missing dependencies when used with React and Webpack

### ISSUE THREAD

**Issue by mrvini** [balderdashy/sails.io.js#80]
Hi

I've been using sails.io.js library for a month or so and it was all working fine till yesterday. 

I am using React with webpack v1.12.10 and webpack-dev-server v1.14.0
node v4.2.3

Yesterday, I've re-run `npm i`, and starting webpack dev server and after this, I am observing the following missing dependencies errors

```bash
WARNING in ./~/ws/lib/BufferUtil.js
Module not found: Error: Cannot resolve module 'bufferutil' in /home/yyyy/Projects/A_Components/node_modules/ws/lib
 @ ./~/ws/lib/BufferUtil.js 10:19-40

WARNING in ./~/ws/lib/Validation.js
Module not found: Error: Cannot resolve module 'utf-8-validate' in /home/yyyy/Projects/A_Components/node_modules/ws/lib
 @ ./~/ws/lib/Validation.js 10:19-44

WARNING in ./~/yyyy-services/~/sails.io.js/~/request/lib/optional.js
Critical dependencies:

```

I don't believe that sails.io.js has anything to do with this, rather it has to do with request package.

AND I can run it perfectly fine from node on the command line

Any Advice?

**Comment by sgress454** [comment]
Is that the whole log?  It looks like the relevant part might be after `Critical dependencies`.

Also, is this causing any actual problems in usage, or is it just the warnings?

I was unable to recreate, you might try doing `npm cache clean`, wiping out your `node_modules` folder and doing `npm i` again...

**Comment by mrvini** [comment]
Thank you @sgress454 , I did miss last line from the log when copied from terminal. Please see the full warning and critical dependencies log below

```
WARNING in ./~/ws/lib/Validation.js
Module not found: Error: Cannot resolve module 'utf-8-validate' in /home/yyyy/Projects/A_Components/node_modules/ws/lib
 @ ./~/ws/lib/Validation.js 10:19-44

WARNING in ./~/ws/lib/BufferUtil.js
Module not found: Error: Cannot resolve module 'bufferutil' in /home/yyyy/Projects/A_Components/node_modules/ws/lib
 @ ./~/ws/lib/BufferUtil.js 10:19-40

WARNING in ./~/yyyy-services/~/sails.io.js/~/request/lib/optional.js
Critical dependencies:
3:11-26 the request of a dependency is an expression
 @ ./~/yyyy-services/~/sails.io.js/~/request/lib/optional.js 3:11-26
webpack: bundle is now VALID.

```

I did run ```npm cache clean``` and removed and reinstalled node modules

While i can start the application on the localhost:8080, i can't make websocket request

**Comment by sgress454** [comment]
I'm afraid I don't really know anything about Webpack.  There was a new release of `sails.io.js` two days ago, which updated the `socket.io-client` dependency, but that's all.  That dependency just got another upgrade so we'll be pushing out a new version of `sails.io.js` again today, but I can only test it against Sails apps.

**Comment by mrvini** [comment]
got you, thanks a lot @sgress454 for your help, I'll keep debugging, sails.io.js is very useful. Once I'll figure out I'll reopen this issue. Thanks again

**Comment by mrvini** [comment]
this issue is with latest 'ws' and 'webpack' reported here socketio/socket.io-client#933
