### ISSUE TITLE
Socket Disconnect Issue on Route/Partial View Change.

### ISSUE THREAD

**Issue by rishab-yumist** [balderdashy/sails.io.js#86]
Hello,

Once I use a socket listener in a view using Sails-Angular and change the view, the socket listener doesn't disconnect.
       
      //Socket Listener in Angular JS
      io.socket.on('dcOrders', function(diff,jwres) {

          $scope.dc.orders = diff.data;

          $scope.$digest();
          if(jwres) console.log("Error retrieving orders details for DC.");
      });

If I use io.socket.disconnect(); on routeChange, it fails to reconnect to the socket on same url when I reload the view.

I tried adding the connect and disconnect listeners as well.

 io.socket.on('connect', function(){
      $scope.getOrdersForDC();
    });

 io.socket.on('disconnect', function(){
      Utils.reconnectingNotification("RECONNECTING..");
    });

Could someone help me disconnect the view/remove the listener on route change?

**Comment by rishab-yumist** [comment]
Hello,

Once I use a socket listener in a view using Sails-Angular and change the view, the socket listener doesn't disconnect.
       
      //Socket Listener in Angular JS
      io.socket.on('dcOrders', function(diff,jwres) {

          $scope.dc.orders = diff.data;

          $scope.$digest();
          if(jwres) console.log("Error retrieving orders details for DC.");
      });


If I use io.socket.disconnect(); on routeChange, it fails to reconnect to the socket on same url when I reload the view.

I tried adding the connect and disconnect listeners as well.

 `io.socket.on('connect', function(){
      $scope.getOrdersForDC();
    });

 io.socket.on('disconnect', function(){
      Utils.reconnectingNotification("RECONNECTING..");
    });`

Could someone help me disconnect the view/remove the listener on route change?

**Comment by rishab-yumist** [comment]
`
 io.socket.on('connect', function(){
      $scope.getOrdersForDC();
    });

 io.socket.on('disconnect', function(){
      Utils.reconnectingNotification("RECONNECTING..");
    });`

**Comment by sgress454** [comment]
Hi @rishab-yumist, I think this is better posted in the [sails-angular](https://github.com/janpantel/angular-sails) repo; it's possible that it needs some updates to work with the latest sails.io.js, or that it's another issue entirely.
