### ISSUE TITLE
Method Not Allowed (ERROR 405)

### ISSUE THREAD

**Issue by alfredobarron** [balderdashy/sails.io.js#90]
I got this problem on my server, help!

<img width="1229" alt="captura de pantalla 2016-02-22 a las 11 59 05 p m" src="https://cloud.githubusercontent.com/assets/2327016/13243016/63186a5c-d9c0-11e5-9610-459eebf23d8f.png">

**Comment by sgress454** [comment]
HI @alfredobarron, sorry for the delay.  I'm afraid there's not really much information to go on here.  The request that's causing the error there is the standard connection request from socket.io.  If the code works locally and not on Amazon, that would point to your Amazon setup as the issue.

Besides Googling around for issues using socket.io with Amazon, I'd also try setting `io.sails.transports=["websocket"]` in the file where you include `sails.io.js` (see [here](s) for more info), and changing `sails.sockets.transports=["websocket"]` on the server (see [here](http://sailsjs.org/documentation/reference/configuration/sails-config-sockets#?commonlyused-options)).  If you happen to have a load balancer in your setup, using the polling transport can cause some problems (see [this note](http://sailsjs.org/documentation/concepts/deployment/scaling#?notes) in the Sails scaling docs).

**Comment by alfredobarron** [comment]
The problem was that the script was not located immediately after sails.io.js

solved here!!
<img width="649" alt="captura de pantalla 2016-03-22 a las 11 37 15 a m" src="https://cloud.githubusercontent.com/assets/2327016/13961485/7af81212-f022-11e5-8bae-ec3a19f1eb85.png">

**Comment by sgress454** [comment]
Ah, glad you got it.  FYI with the newest version of `sails.io.js`, you can use HTML attributes to configure the module, so you don't have to worry about script placement.  See [here](http://sailsjs.org/documentation/reference/web-sockets/socket-client#?basic-configuration-using-html-attributes) for details.
