### ISSUE TITLE
'Uncaught TypeError: Cannot read property 'removeChild' of null'" being thrown by sails.io.js on line 200

### ISSUE THREAD

**Issue by kpturner** [balderdashy/sails.io.js#92]
I keep getting this error every so often on the browser. I cannot seem to track down any particular pattern. Can anybody point me in the right direction as to when this function is likely to be called. It doesn't seem to coincide with any user interaction.

The browser appears to be idle at the time but I cannot be 100% sure.   I am off playing on another browser tab, then go back to the sails app and voila, there it is.   It doesn't appear to be related to shutting down the server unexpectedly or restarting it either.  

There is no version number in sails.io.js (at least not in my version) but the server is on Sails v0.11.2

The client code is nothing to do with sails by the way.  It just happens to make use of socket.io.js and sails.io.js for web socket functionality.  The server it talks to is an extremely lightweight Sails app that is only used for web socket functionality.

**Comment by sgress454** [comment]
> There is no version number in sails.io.js
In the browser console, you should see a message when sails.io.js connects, like:
```
  |>    Now connected to Sails.
\___/   For help, see: http://bit.ly/1DmTvgK
        (using browser SDK @v0.11.0)
```

**Comment by kpturner** [comment]
Ahh yes - (using browser SDK @v0.11.0)

**Comment by sgress454** [comment]
Hm, would you be able to post the contents of your client-side file in a [Gist](https://gist.github.com/)?

**Comment by kpturner** [comment]
Happy to oblige - but what do you mean by "client-side file" ?

The JavaScript assets on that application are positively enormous, so I am sure you won't want all of that.

**Comment by sgress454** [comment]
I just mean the HTML file that's loading `sails.io.js`.

**Comment by kpturner** [comment]
OK - well it is not loaded within an HTML file as such.  It is a(n) SPA and is loaded on the fly with require.js like this:
 
`require(["sails/socket.io", "sails/sails.io", "rns", "rns.console", "rns.websocket"], function(socketIOClient, sailsIOClient) {
RNS.Sails = (function () {
var me = {};
me.createConnector=function(){
me.io=sailsIOClient(socketIOClient);
}
return me;
}()) 
})` 


So it gets create by
`RNS.Sails.createConnector()`
elsewhere.


Does this help?

**Comment by sgress454** [comment]
Erm.  Maybe.  So the code that's throwing the error is the JSONP callback.  When `sails.io.js` detects that it's being asked to connect cross-domain (determined by looking at the values of `io.sails.url` and `window.location`), it makes a JSONP request to `/__getcookie` on that domain which, when loaded into a `<script>` tag, runs the `_sailsIoJSConnect()` method which just removes that script tag.  The purpose here is to make sure a cookie is loaded from the foreign domain so that a session can be established.  The error that's being thrown in your case seems to indicate that the `_sailsIoJSConnect()` method is being called again after the tag has already been removed, or else that the tag is somehow being removed between the JSONP call and the response.

**Comment by kpturner** [comment]
It certainly helps to understand when it gets called.  Im my case the domain is always the same, but the port is different. I can see the` __getcookie` being run when I fire up the page.  Are there any circumstances where it would be called again other than the page being completely refreshed (either by the user or via a JavaScript call to` location.reload()` ?

**Comment by kpturner** [comment]
Much as it goes against my better judgement, I have had to patch sails.io.js for the time being because it was driving everyone nuts, and socket functionality seemed unaffected.  I don't expect you to put the patch into your version (although that would be nice),  It seems to be an unusual set of circumstances, unless you are working here (in Chrome).

If you want, I can close this I will. 

`    /**
     * Send a JSONP request.
     * 
     * @param  {Object}   opts [optional]
     * @param  {Function} cb
     * @return {XMLHttpRequest}
     */

    function jsonp(opts, cb) {
      opts = opts || {};

      if (typeof window === 'undefined') {
        // TODO: refactor node usage to live in here
        return cb();
      }

      var scriptEl = document.createElement('script');
      window._sailsIoJSConnect = function(response) {
    	// For some reason scriptEl may have been vaporised before we have the response
    	if(scriptEl && scriptEl.parentNode)
    		scriptEl.parentNode.removeChild(scriptEl);
        
        cb(response);
      };
      scriptEl.src = opts.url;
      document.getElementsByTagName('head')[0].appendChild(scriptEl);

    }`

**Comment by sgress454** [comment]
If you want to put that in a pull request (with brackets around the `removeChild` line, please), I'd be fine merging it, although I'd still like to know why it's happening in the first place.  Can you put a log in `_sailsIoJSConnect` and see if it's being called multiple times?

**Comment by kpturner** [comment]
Presumably you mean braces - like this:
`if(scriptEl && scriptEl.parentNode) {
        scriptEl.parentNode.removeChild(scriptEl);
}`

Yeah I will try some more logging.  I fiddled for ages over the weekend trying to work out scenarios where this could happen and got precisely nowhere.  Then when the masses were let lose in our dev shop this morning - instant flags going up with the error.

It is definitely linked to a window.reload taking place - we have a mechanism where people can push hotfixes to everyone by hitting the browser sessions (via a websocket connection) inviting them to do a reload to pick up fixes.  After that (only sometimes) this error may occur once or several times at once.   

In any given sessions, there may be several components on a screen that may attempt to connect to the web socket server.  I think there is some sort of lag in the connection request that makes it take longer than expected, but it still doesn't explain why the <head> has changed.  It is as if a __getcookie is taking ages to get a reponse, and in the meantime the window has reloaded - but then I would expect the __getcookie request to be vaporised as well.

**Comment by sgress454** [comment]
> Presumably you mean braces 

Yup, thanks.

> In any given sessions, there may be several components on a screen that may attempt to connect to the web socket server.

Hmm, well if there were _several_ requests for `__getcookie`, and they came in out-of-order, maybe one could remove the other's script tag?  But it doesn't seem likely since `scriptEl` is a local var...

**Comment by kpturner** [comment]
As I still haven't managed to replicate it myself I don't know if there are several __getcookie requests or not.  Each component should be sharing the same "connection" in a different namespaced component anyway - and as you say it is a local var so it seems unlikely that the code is screwing itself :)

**Comment by kpturner** [comment]
I made the change locally and committed.  Being a bit of a github newb, how should I go about creating  a pull request for you to merge in?

**Comment by sgress454** [comment]
Welp, we used to have some instructions but they appear to have been removed.  So!

1. Fork the `sails.io.js` repo by clicking the "fork" button at the top of the Github page.
2. Clone the forked repo to your computer with `git clone <URL of forked repo>`
3. Make the change locally and commit (apologies if you've already done these three steps)
4. Run `npm test` to make sure the tests still pass
5. Push the change to your forked Github repo with `git push -u origin master`
6. Back in Github, go to the home page for your forked repo and you should see a "Create pull request" button or something similar.  Press it and follow the instructions.  Please title the pull request `[PATCH] Fixes #92`

Thanks!

**Comment by kpturner** [comment]
OK - well what I hadn't done was run `npm test`  -  presumably before I can do that I need to run `npm install` on the freshly cloned repo.  Unfortunately that barfs on my windows 10 machine.
![image](https://cloud.githubusercontent.com/assets/308646/13396973/78d88e24-deef-11e5-930a-58fd86033018.png)

**Comment by sgress454** [comment]
Oh lord.  Ok, don't worry about the tests, I'll run them here.

**Comment by sgress454** [comment]
Thanks again @kpturner.  If you ever do get more details on this, feel free to post here.
